-- PROSEDÜR

--CREATE PROCEDURE HAREKETLER
--AS
--SELECT HAREKETID,URUNAD,MUSTERIAD + ' ' + MUSTERISOYAD AS 'AD SOYAD', PERSONALADSOYAD,TUTAR,TARIH
--FROM TBLHAREKET INNER JOIN TBLURUNLER ON TBLHAREKET.URUN = TBLURUNLER.URUNID
--INNER JOIN TBLMUSTERI ON TBLHAREKET.MUSTERI=TBLMUSTERI.MUSTERIID
--INNER JOIN TBLPERSONEL ON TBLPERSONEL.PERSONELID=TBLHAREKET.PERSONEL

--EXECUTE HAREKETLER


--ALTER PROCEDURE URUNGETIR
--@Deger varchar (50)='BUZDOLABI'
--AS
--SELECT URUNAD,URUNSTOK,URUNMARKA FROM TBLURUNLER
--WHERE URUNAD=@Deger

--EXECUTE URUNGETIR @Deger='LAPTOP'





--SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3
-- 1 VE 3 EKÝM ARASINDAKÝ DEÐERLERÝ GETÝRÝR. GÜNE GÖRE.


--SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3
--AND MUSTERI=(SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR='ANKARA')
--ANKARALI MÜÞTERÝNÝN 1 VE 3 EKÝM ARASINDA YAPTIÐI ALIÞVERÝÞLER.


--SELECT DATENAME(MONTH,GETDATE()), DATENAME(MONTH,'2019.01.15')
-- O ANKÝ VEYA ÝSTENÝLEN TARÝHTEKÝ TARÝHÝN BÝLGÝLERÝNÝ GETÝRÝR.

--SELECT DATENAME(WEEKDAY,GETDATE())
-- BUGÜN PAZARMIÞ

--SELECT DATENAME(WEEKDAY,'2024.03.26')
--2024TE DOÐUM GÜNÜM SALIYA GELÝYORMUÞ.


--SELECT DATEDIFF(YEAR,'2010.10.25',GETDATE())
--10 YIL GEÇMÝÞ BU TARÝHTEN SONRA.

--SELECT DATEDIFF(DAY,TARIH,GETDATE()) FROM TBLHAREKET WHERE HAREKETID=1
-- 446 GÜN GEÇMÝÞ ÝLK SATIÞ YAPILALI.


--SELECT DATEADD(DAY,29281,'1995.03.26')
-- DOÐUM GÜNÜME 9999 GÜN EKLERSEM 10 AÐUSTOS 2022 EDÝYORMUÞ :O

--SELECT DATEDIFF(DAY,'1995.03.26',GETDATE())
--SELECT DATEDIFF(DAY,'1960.02.23',GETDATE())
--SELECT DATEDIFF(DAY,'1938.10.08','2018.12.08')

-------------------------------------------------------------


--SELECT * FROM TBLHAREKET WHERE URUN IN(SELECT URUNID FROM TBLURUNLER
--WHERE KATEGORI=1)
-- 1DEN FAZLA DÖNÜÞ VARSA SUBQUERY'DE "IN" KULLANIRIZ. YOKSA HATA VERÝR.


--SELECT * FROM TBLHAREKET WHERE URUN IN(SELECT URUNID FROM TBLURUNLER
--WHERE KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BÝLGÝSAYAR'))
--HAREKET TABLOSUNDA SATILAN BÝLGÝSAYAR VERÝLERÝNÝ GETÝR.


--SELECT * FROM TBLHAREKET WHERE MUSTERI IN(SELECT MUSTERIID FROM TBLMUSTERI
--WHERE MUSTERISEHIR='ADANA')
--ADANALI MÜÞTERÝLERÝN YAPTIÐI HARCAMALARI GETÝRÝR.


--SELECT * FROM TBLHAREKET WHERE URUN IN (SELECT URUNID FROM TBLURUNLER
--WHERE KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BEYAZ EÞYA'))
-- SATILAN BEYAZ EÞYALARIN BÝLGÝLERÝNÝ GÖSTERÝYOR.


--SELECT SUM(TUTAR) FROM TBLHAREKET WHERE MUSTERI IN(SELECT MUSTERIID
--FROM TBLMUSTERI WHERE MUSTERISEHIR IN('ADANA','ANKARA','BURSA'))
--ADANA ANKARA VE BURSALI MÜÞTERÝLERÝN SATILAN MALLARIN TOPLAM TUTARI.


--UPDATE TBLURUNLER SET URUNSTOK= URUNSTOK - (SELECT SUM(ADET)
--FROM TBLHAREKET WHERE URUN=10) WHERE URUNID=10
-- SONDA WHERE URUNID=1 DEMEZSEK 
--TÜM ÜRÜNLER ÝÇÝN 1 NOLU ÜRÜNÜN SATILDIÐI KADAR STOKTAN AZALTIR.
--ALTSORGU ÝLE SADECE TOPLAM SATILAN SAYISINI GETÝRDÝK.
--BURASI OLMASA BÝLE WHERE URUNID=1 KISMI MUTLAKA OLMALIYDI 
--YOKSA HER YERÝ ETKÝLER.. ÇOK ÖNEMLÝ BÝR NOKTA BENCE.!!!

----------------------------------------------


--CREATE TABLE TBLKASA
--(
--TOPLAM DECIMAL(18,2)
--)

--INSERT INTO TBLKASA VALUES (0)
--SELECT * FROM TBLKASA
--UPDATE TBLKASA SET TOPLAM=TOPLAM+(SELECT SUM(TUTAR) FROM TBLHAREKET)
-- KASAMIZDA 43.718 LÝRA VARMIÞ.TOPLAM SATIÞ TUTARLARINI GÖNDERDÝK.

----------------------------------------------------

-- ÞÝMDÝ OLAYLARI TETÝKLEYÝCÝ ÝLE YAPALIM.



--CREATE TABLE TBLSAYAC
--(
--ISLEM INT
--)

--INSERT INTO TBLSAYAC VALUES(0)

--HAREKET TABLOLARINDAKÝ SATIÞ SAYIMIZI YAZDIRALIM.
--UPDATE TBLSAYAC SET ISLEM=(SELECT COUNT(*) FROM TBLHAREKET)

--CREATE TRIGGER ISLEMARTIS
--ON TBLHAREKET
--AFTER INSERT 
--AS
--UPDATE TBLSAYAC SET ISLEM = ISLEM +1

--------------------
--2. ÖRNEK

--CREATE TABLE TBLTOPLAMKATEGORI
--(
--ADET TINYINT
--)

--UPDATE TBLTOPLAMKATEGORI SET ADET=(SELECT COUNT(*) FROM TBLKATEGORI)

--CREATE TRIGGER KATEGORIARTIS
--ON TBLKATEGORI
--AFTER INSERT
--AS
--UPDATE TBLTOPLAMKATEGORI SET ADET += 1

--CREATE TRIGGER KATEGORIAZALIS
--ON TBLKATEGORI
--AFTER DELETE
--AS
--UPDATE TBLTOPLAMKATEGORI SET ADET -= 1


-----------------------



--VÝEW

--CREATE VIEW TEST1
--AS SELECT * FROM TBLKATEGORI

--SELECT * FROM TEST1

--ALTER VIEW TEST1 
--AS 
--SELECT * FROM TBLKATEGORI WHERE KATEGORIID<4

--SELECT * FROM TEST1

--SELECT * FROM TEST3